/*
    *  THIS TRIGGER WILL BE TRIGGERED WHEN A CHART IS DELETED
    *  IT WILL DELETE THE WIDGET THAT CONTAINS THE CHART
    *  THIS IS TO OVERCOME THE FOLLOWING ISSUE
        * WHEN A COLUMN IS DELETED FROM THE COLUMNS TABLE,
            * GAUGES
            * TOGGLES
            * RELEVANT ROWS FROM PARAMTER TABLES
            * RELEVANT ROWS FROM CHART SERIES TABLE
            * CHARTS
            WILL BE DELETED
        * WHEN ANY OF THE ABOVE DELETED, IT WILL MANIPULATE CREATED WIDGETS EXCEPT
            * WHEN THERE ARE MORE COLUMNS FOR PARAMETER TABLES
            * WHEN THERE ARE MORE CHART SERIES FOR CHARTS
        * SO, WHEN A TOGGLE OR GAUGE IS DELETED, THE WIDGET WILL BE DELETED AUTOMATICALLY
    *  BEFORE CREATING THIS TRIGGER, CREATE THE FUNCTION delete_from_widget
*/
CREATE OR REPLACE TRIGGER after_delete_chart AFTER
DELETE ON "iot-on-earth-public".charts
FOR EACH ROW EXECUTE FUNCTION "iot-on-earth-public".delete_from_widget();