/*
    * THIS IS A FUNCTION THAT DELTES A ROW FROM WIDGET TABLE
    * TRIGGERS WILL BE CREATED TO TRIGGER THIS FUNCTION
        * WHEN A TOGGLE IS DELETED FROM TOGGLES TABLE
        * WHEN A GAUGE IS DELETED FROM GAUGES TABLE
    * WHY THIS?
        * WHEN A COLUMN IS DELETED FROM THE COLUMNS TABLE,
            * GAUGES
            * TOGGLES
            * RELEVANT ROWS FROM PARAMTER TABLES
            * RELEVANT ROWS FROM CHART SERIES TABLE
            * CHARTS
            WILL BE DELETED
        * WHEN ANY OF THE ABOVE DELETED, IT WILL MANIPULATE CREATED WIDGETS EXCEPT
            * WHEN THERE ARE MORE COLUMNS FOR PARAMETER TABLES
            * WHEN THERE ARE MORE CHART SERIES FOR CHARTS
        * SO, WHEN A TOGGLE OR GAUGE IS DELETED, THE WIDGET WILL BE DELETED AUTOMATICALLY
*/
CREATE OR REPLACE FUNCTION "iot-on-earth-public".delete_from_widget() RETURNS TRIGGER AS $$
BEGIN
  DELETE FROM "iot-on-earth-public".widgets WHERE id = OLD.widget_id;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;